<?php
/**
 * @var \Smart\Bloger\Block\Search $block
 */
?>
    <?php foreach ($block->searchByKeyword() as $key=>$post):?>
        <?php if(!empty($post->getPostName())): ?>
            <div class="list clearfix">
                <div class="indexblock">
                    <a href="<?php echo $this->getUrl('*/*/detail', array('idpost' => $post->getPostId())); ?>">
<!--                    <a href="detail?idpost=--><?php //echo $post->getPostId(); ?><!-- ">-->
                        <img src="<?php echo $post->getPostImage(); ?>" class="image"/>
                        <h2><b><?= $post->getPostName(); ?></b></h2>
                    </a>
                    <h3>
                        <p><?=$post->getPostTitle(); ?></p>
                        <p><?=$post->getPostShortdescription(); ?></p>
                    </h3>

                </div>
            </div>
            <?php else:?>
        <h3>khoong dc</h3>
        <?php endif;?>
    <?php endforeach;?>

<style>
    .list {
        border: 3px solid white;
        padding: 4px;
        overflow: hidden;
    }
    .image {
        float: left;
        width: 300px;
        height: 200px;
        margin-right: 20px;
    }
    .clearfix {
        overflow: auto;
    }
    .list .indexblock a{
        text-decoration: none;
    }


</style>