<?php
//@codingStandardsIgnoreFile

/** @var $block \SmartOSC\Blog\Block\Sidebar\CategoryTree */
?>

<div class="block block-collapsible-nav blog__sidebar-category-tree">

    <div class="title block-collapsible-nav-title"
         data-mage-init='{"toggleAdvanced": {"toggleContainers": "#block-collapsible-nav-blog", "selectorsToggleClass": "active"}}'>
        <strong><?= __('Categories') ?></strong>
    </div>
    <div class="block-collapsible-content content" id="block-collapsible-nav-blog">
        <ul class="nav items">
            <?php foreach ($block->testgetTree() as $key => $category): ?>
                <li class="nav item category<?= $category->getCategoryId();?> categoryid" value="<?= $category->getCategoryId(); ?>"><?= $category->getCategoryName()?>
                        <?php if($category->getParentId()==$category->getCategoryId()){?>
                            <ul class="category-child">
                                <li class="nav item category-child<?= $category->getCategoryId(); ?> categoryid" value="<?= $category->getCategoryId(); ?>"><a href="<?= $category->getCategoryUrl(); ?>"><?= $category->getCategoryName(); unset($category[$key]); ?></a></li>
                            </ul>
                </li>
                        <?php }?>
                    <?php endforeach ?>
        </ul>
    </div>
</div>
